### ISSUE TITLE
does this help with semantic-ui?

### ISSUE THREAD

**Issue by cordoval** [crossborne/gassetic#50]
it seems this is not needed when using semantic-ui right?

I am trying to create a gulpfile that just merges my assets from semantic-ui and my project assets but i am not using bundles on symfony all assets are managed via gulp

**Comment by crossborne** [comment]
Yea it seems that semantic-ui have their own build system.

You do not need to use assets from the Symfony bundles, that was one of the reasons gassetic was built  - It enables you to use bower components instead.

**Comment by cordoval** [comment]
yeah i actually remove assetic already from symfony projects :+1: thanks for confirming
